print("MadLibs Game")

adjective1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
place = input("Enter a place: ")
piece_of_clothing = input("Enter a piece of clothing: ")
adjective2 = input("Enter an adjective: ")
adjective3 = input("Enter an adjective: ")
adjective4 = input("Enter an adjective: ")
adjective5 = input("Enter an adjective: ")
song_title = input("Enter a song title: ")
food = input("Enter food: ")
adjective6 = input("Enter an adjective: ")
past_tense_verb1 = input("Enter a past tense verb: ")
noun2 = input("Enter a noun: ")
noun3 = input("Enter a noun: ")
past_tense_verb2 = input("Enter a past tense verb: ")
past_tense_verb3 = input("Enter a past tense verb: ")
noun4 = input("Enter a noun: ")
noun5 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
verb2 = input("Enter a verb: ")
verb3 = input("Enter a verb: ")
adjective7 = input("Enter an adjective: ")

print("It was a " + adjective1 + " summer day.")
print(noun1 + " and I were excited to go camping at " + place + ".")
print("It was my first time going there.")
print("I packed my favourite " + piece_of_clothing + ".")
print("It is " + adjective2 + " and " + adjective3 + ".")
print("Perfect for camping!")
print("On the road we went in our " + adjective4 + " " + adjective5 + " van!")
print("We were listening to " + song_title + " all the way down.")
print("The drive was about 5 hours but it was so worth it.")
print("When we got there we unpacked the van.")
print("I could smell " + food + " being cooked.")
print("It smelled " + adjective6 + ".")
print("I " + past_tense_verb1 + " to the room I was staying in with my " + noun2 + ".")
print("The next thing I knew, " + noun3 + " came and " + past_tense_verb2 + " on the bed.")
print("I heard my mom scream, 'Get off the bed!' I " + past_tense_verb3 + " outside.")
print("I saw " + noun4 + ".")
print("It was " + noun5 + ".")
print("Over the next few days I got to " + verb1 + ", " + verb2 + ", and " + verb3 + ".")
print("My camping trip was " + adjective7 + ".")